# Generated by Django 4.2.24 on 2025-10-26 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("whatsapp", "0002_whatsappcampaign"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whatsappcampaign",
            name="campaign",
        ),
        migrations.AlterField(
            model_name="whatsappcampaign",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="whatsappcampaign",
            name="target_contacts",
            field=models.ManyToManyField(
                related_name="campaigns", to="whatsapp.whatsappcontact"
            ),
        ),
        migrations.AlterField(
            model_name="whatsappcampaign",
            name="whatsapp_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="whatsapp.whatsappinstance",
            ),
        ),
    ]
