# Generated by Django 4.2.24 on 2025-09-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_alter_historicalplan_stripe_price_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubscription",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Stripe Customer ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubscription",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Stripe Subscription ID",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Stripe Customer ID"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Stripe Subscription ID",
            ),
        ),
    ]
